### ISSUE TITLE
Condon Errors

### ISSUE THREAD

**Issue by halecatherine** [PaulHancock/Aegean#126]
I was looking at the calculation of Condon errors and am finding some discrepancies when Aegean is calculating them to what I believed the output should be when calculating them directly from the Condon equations. Specifically when calculating the values, I have confusion over the lines:

``` python    
smoothing = major * minor / (theta_n ** 2)
factor1 = (1 + (major / theta_n))
factor2 = (1 + (minor / theta_n))
```

(Lines 881-883 in fitting.py)

For a circular beam (of N" FWHM), I am finding that smoothing appears to be a factor of two smaller than expected - and it appears theta_n might not be the value as expected (N"), but sqrt(2.)*N

Also, the factor values appear discrepant to the equations in the Condon 1997 paper (http://articles.adsabs.harvard.edu/pdf/1997PASP..109..166C, Eq 41) as they miss the squared and appear to have major/theta_n etc the wrong way around. I think it should instead be:

``` python    
factor1 = (1 + (theta_n/major)**2)
factor2 = (1 + (theta_n/minor)**2)
```

**Comment by PaulHancock** [comment]
Thanks @halecatherine. I think you are right about Eq 41 - it's not implemented as written.

Condon '97 assumes a single smoothing factor of θ_N which is effectively a circular point spread function. To allow for an elliptical psf I want to compute the "average smoothing factor", which should be sqrt(a*b) rather than hypot(a,b). So yes, there is a second issue here.
