### ISSUE TITLE
May give a clarrification of position angle (PA)?

### ISSUE THREAD

**Issue by mahengrui1** [PaulHancock/Aegean#87]
Hi, idk what s the meaning of PA

  --beam BEAM BEAM BEAM
                        The beam parameters to be used is "--beam major minor
                        pa" all in degrees. [default: read from fits header].

in https://github.com/PaulHancock/Aegean/wiki/Quick-Start-Guide the pa is linked to wikipedia, but i dont think the 'angle measured relative to the north celestial pole (NCP), turning positive into the direction of the right ascension.' is very clear to me. so let me ask

is pa (-90,90)? when it s 0, the long axis (a) of elliptical is parallel to Meridian, when it s +/-90, parallel to circle of latitude. In a standard image (RA is larger at right and DEC +90 is on top), if we rotate a source by a clockwise angle the theta will increases a bit, right?

Reference: https://en.wikipedia.org/wiki/Gaussian_function

**Comment by PaulHancock** [comment]
The position angle is measured from North towards East. This means that 0 deg is North, and +90 deg is east, -90 deg is west.

The PA should be clipped to be (-90,90) since larger/smaller angles are degenerate.

If your image has RA increasing to the right (which is not normal IMO), then a clockwise rotation will increase the PA.
