### ISSUE TITLE
why int_flux increases when --beam decreases

### ISSUE THREAD

**Issue by mahengrui1** [PaulHancock/Aegean#89]
I try several --beam parameter, when beam goes smaller, the peak flux is stable, great, but int flux goes bigger.

But as my understanding, int flux is calculated by size and peak, shows the Jy of source a constant. 
I check peak flux and a and b are similar, but int goes bigger or even double when I change beam from 1.2'' to 0.9''

Besides, the int_flux is always smaller than the sum of flux in every pixels, what s the difference between those two?

**Comment by mahengrui1** [comment]
coz 
$int_flux*3.14/(arcsec per pixel)/(arcsec per pixel)*(beam major)*(beam minor)$
is nearly constant.

**Comment by PaulHancock** [comment]
Int flux getting larger when `--beam is made` smaller
----------------------------------------------------------

If you make the synthesized beam smaller, then then it will not affect the *fitted* flux/shape of the source. However the integrated flux is not fit, it is computed from the fit parameters as you have indicated: `int_flux = peak_flux * a * b / (psf_a * psf_b)`

If you have a point source then it will be fit with a shape that is about the same as the (actual) synthesized beam, but if you are artificially making the synthesized beam smaller then a point source will look like it's larger than the synthesized beam so that  the factor ` a*b/(psf_a*psf_b)` is no longer unity.

The difference between integrated flux for island and component
------------------------------------------------------------------------

Sources in the `comp` catalogue are components of an island. They have an integrated flux calculated as above.

Sources in the `isle` catalogue have an integrated flux, which is just the sum of all the pixels. There is no fitting here, just a sum of the fluxes for all the pixels in the island. The difference between the two is that, for a point source, there is some flux left in the *wings* of the integral. What I mean is that the integral is over the entire Gaussian ellipse, but the summation is only over the pixels that are above the flood threshold. This will mean for point sources that some fraction of the total flux is not counted. The parameter `ita` in the `isle` catalogue is meant to be the factor by which the two integrated fluxes differ, however this is only really correct for an island with a single point source in it (so it's only mildly useful).

**Comment by mahengrui1** [comment]
hi, thx a lot. i have a question about int_flux, now i think int_flux in 'comp' file (not the island) is larger than i expected. i m not very experienced in python so there may be error in my derivation:

i checked in Aegean it is:

int_flux = peak_flux * a * b / (psf_a * psf_b)

as u said. but if we assume an 2D Gaussian, in this formula the a and b should be sth like variance, in wikipedia 'Gaussian_function'

 the int is given by

    V = ∫ − ∞ ∞ ∫ − ∞ ∞ f ( x , y ) d x d y = 2 π A σ X σ Y 

(Two-dimensional Gaussian function)

but in ur code https://aegeantools.readthedocs.io/en/latest/_modules/AegeanTools/source_finder.html

it is


```
            # calculate integrated flux
            source.int_flux = source.peak_flux * sx * sy * CC2FHWM ** 2 * np.pi
            # scale Jy/beam -> Jy using the area of the beam
            source.int_flux /= global_data.psfhelper.get_beamarea_pix(source.ra, source.dec)

```
where sx and sy is CC ( σ X and σ Y), and u convert it to FHWM, idk why u convert it. the second line means divided by pi * psf_a *psf_b i guess, so the whole formula is what u said. but i think u miss an factor 2 above and shouldnt use FHWM (FWHM??) so i d use

```
            # calculate integrated flux
            source.int_flux = source.peak_flux * sx * sy * 2 * np.pi
            # scale Jy/beam -> Jy using the area of the beam
            source.int_flux /= global_data.psfhelper.get_beamarea_pix(source.ra, source.dec)

```

maybe i dont understand sx and sy correctly or maybe idk the math to integral 2D-Gaussian using FWHM directly.

**Comment by mahengrui1** [comment]
hi, pls just ignore what i said 22 hours ago, that s a conversion from the int_flux value to counts. i forget that step.
