### ISSUE TITLE
Priorized fitting fits negative fluxes, even when --negative isn't set

### ISSUE THREAD

**Issue by PaulHancock** [PaulHancock/Aegean#93]
The option `--negative` should turn ON the reporting/fitting of negative sources, however in `--priorized` mode this isn't the case.

Recommend that `--priorized` fitting fits only positive fluxes, and that `--negative` allows the fitted fluxes to be negative.

**Comment by PaulHancock** [comment]
This has been changed in the dev branch in commit c4a9be8

**Comment by PaulHancock** [comment]
Thankfully this feature never made it to the master branch.

**Comment by KasVeken** [comment]
Good Afternoon @PaulHancock,

I am a master student from Leiden and I'm working on a radio astronomy master project (supervised by Joe Callingham and Huub Rottgering). I use your Aegean to find my desired sources in LOFAR data and consequently make time series and spectra of predominantly M-Dwarfs. Since last week I am using the --priorized fitting option to make a forced fit on my images. It seems that I run into exactly this problem. In the cases in which I don't want to report/fit negative values, it still does, eventhough I haven't typed '--negative'. 

I run it via the 'os.system' command line in python as:

os.system('aegean --autoload  --priorized 1 --input '+forced_fitter_path+input.fits --floodclip -1 --table '+filename.split('image.fits')[0]+'_output.fits '+filename)

or when I do want negative values: 
os.system('aegean --autoload  --negative --priorized 1 --input '+forced_fitter_path+input.fits --floodclip -1 --table '+filename.split('image.fits')[0]+'_output.fits '+filename)

Both lines result in the same values, positve + negative, instead of just positive for the first one. 

Do you have any idea what I should do?

**Comment by PaulHancock** [comment]
Hi @KasVeken. For priorized fitting you will always get a flux fit at the location that you provide, even if the best fit is negative. There is no way to force only positive fluxes to be fit. You can filter the negative fluxes if you don't like them, but I would argue that they are adding valid information to your light curves and should be retained.

This ticket was closed because I realised that the bug didn't exist - the `--negative` option is only for filtering of blind detections, not for priorized fits.

**Comment by KasVeken** [comment]
Okay, thank you for your quick respons! Sorry for the inconvenience, 

Kas Veken
